#!/usr/bin/env bash

PROJECT_NAME="libzeropool_wasm"
FILE_NAME="libzeropool_wasm.wasm"

wasm-pack build
wasm-opt -o pkg/wasm-opt.wasm -O3 pkg/${PROJECT_NAME}_bg.wasm && mv pkg/wasm-opt.wasm pkg/${PROJECT_NAME}_bg.wasm
