#!/usr/bin/env bash

PROJECT_NAME="libzeropool_wasm"
FILE_NAME="libzeropool_wasm.wasm"

wasm-pack build
wasm-opt -o lib/wasm-opt.wasm -O3 lib/${PROJECT_NAME}_bg.wasm && mv lib/wasm-opt.wasm lib/${PROJECT_NAME}_bg.wasm
