#!/usr/bin/env bash

PROJECT_NAME="libzeropool_wasm"
FILE_NAME="libzeropool_wasm.wasm"

cargo build --lib --release --target wasm32-unknown-unknown
wasm-bindgen target/wasm32-unknown-unknown/release/${FILE_NAME} --out-dir lib --typescript --target bundler
wasm-opt -o lib/wasm-opt.wasm -O3 lib/${PROJECT_NAME}_bg.wasm && mv lib/wasm-opt.wasm lib/${PROJECT_NAME}_bg.wasm
